#!/bin/bash
# Created by 097-026-7262
if [[ -e /etc/debian_version ]]; then
	OS=debian
	RCLOCAL='/etc/rc.local'
elif [[ -e /etc/centos-release || -e /etc/redhat-release ]]; then
	OS=centos
	RCLOCAL='/etc/rc.d/rc.local'
	chmod +x /etc/rc.d/rc.local
else
	echo "ดูเหมือนว่าคุณไม่ได้ใช้ตัวติดตั้งนี้ในระบบ Debian, Ubuntu หรือ CentOS "
	exit
fi
sleep 1
clear
color1='\e[031;1m'
color2='\e[34;1m'
color3='\e[0m'
echo -e "-------------------------------------------------------" | lolcat
	echo ""
	cname=$( awk -F: '/model name/ {name=$2} END {print name}' /proc/cpuinfo )
	cores=$( awk -F: '/model name/ {core++} END {print core}' /proc/cpuinfo )
	freq=$( awk -F: ' /cpu MHz/ {freq=$2} END {print freq}' /proc/cpuinfo )
	tram=$( free -m | awk 'NR==2 {print $2}' )
	swap=$( free -m | awk 'NR==4 {print $2}' )
	up=$(uptime|awk '{ $1=$2=$(NF-6)=$(NF-5)=$(NF-4)=$(NF-3)=$(NF-2)=$(NF-1)=$NF=""; print }')

	echo -e "\e[032;1mCPU model:\e[0m $cname"
	echo -e "\e[032;1mNumber of cores:\e[0m $cores"
	echo -e "\e[032;1mCPU frequency:\e[0m $freq MHz"
	echo -e "\e[032;1mTotal amount of ram:\e[0m $tram MB"
	echo -e "\e[032;1mTotal amount of swap:\e[0m $swap MB"
	echo -e "\e[032;1mSystem uptime:\e[0m $up"
	echo -e "-------------------------------------------------------" | lolcat
	echo -e ">>>>>> [ WWW.FACEBOOK.COM / CEOLNW 097-026-7262 ] <<<<<" | lolcat
	echo -e "-------------------------------------------------------" | lolcat
	echo -e ""
	echo -e "-------------------------------------------------------" | lolcat
	echo -e "|||||||||||||||| เกี่ยวกับการสร้างบัญชี PPTP ||||||||||||||||" | lolcat
	echo -e "-------------------------------------------------------" | lolcat
	echo -e " [+] |${color1}1${color3}| ${color3}สร้างบัญชี PPTP${color3}"
	echo -e " [+] |${color1}2${color3}| ${color3}ลบบัญชี PPTP${color3}"
	echo -e " [+] |${color1}3${color3}| ${color3}ดูรายละเอียดบัญชี PPTP${color3}"
	echo -e " [+] |${color1}4${color3}| ${color3}เช็คบัญชีที่ออนไลน์ PPTP${color3}"
	echo -e " [+] |${color1}5${color3}| ${color3}ดูรายชื่อบัญชีทั้งหมดของ PPTP${color3}"
	echo -e "-------------------------------------------------------" | lolcat
	echo -e "|||||||||||||||||| เกี่ยวกับระบบ Server ||||||||||||||||||" | lolcat
	echo -e "-------------------------------------------------------" | lolcat
	echo -e " [+] |${color1}6${color3}| ${color3}Reboot Server${color3}"
	echo -e " [+] |${color1}7${color3}| ${color3}เปลี่ยน Password VPS${color3}"
	echo -e " [+] |${color1}8${color3}| ${color3}ยกเลิก < ออกไม่เลือกเว้ย >${color3}"

echo -e "-------------------------------------------------------" | lolcat
read -p " [>] เลือกคำสั่งที่ต้องการ (พิมพ์เลข): " x
echo -e "-------------------------------------------------------" | lolcat
if test $x -eq 1; then
user-add-pptp
elif test $x -eq 2; then
user-delete-pptp
elif test $x -eq 3; then
user-detail-pptp
elif test $x -eq 4; then
user-login-pptp
elif test $x -eq 5; then
alluser-pptp
elif test $x -eq 6; then
reboot
elif test $x -eq 7; then
passwd
elif test $x -eq 8; then
echo ""
echo " [>] ติดตามได้ที่ www.facebook.com/ceolnw"
elif test $x -eq ""; then
clear
echo ""
echo " [!] สคริปต์นี้จะทำงานโดยอัตโนมัติทุกๆ 12 ชั่วโมง"
echo " [>] คุณไม่จำเป็นต้องเรียกใช้ด้วยตนเอง"
sleep 10
user-expire
else
echo "ไม่พบตัวเลือกในเมนู."
exit
fi
